### ISSUE TITLE
cannot start confluence-dumper

### ISSUE THREAD

**Issue by Alser84** [siemens/confluence-dumper#1]
Hi, folks.
On CentOS Linux release 7.5.1804 i got error:
mkvirtualenv confluence_dumper_venv
New python executable in /root/root/.virtualenvs/confluence_dumper_venv/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /root/root/.virtuale...mper_venv/bin/python - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "/usr/lib64/python2.7/pkgutil.py", line 581, in get_data
    mod = sys.modules.get(package) or loader.load_module(package)
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-10.0.1-py2.py3-none-any.whl/pip/_vendor/requests/__init__.py", line 83, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/__init__.py", line 42, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/cmdoptions.py", line 16, in <module>
  File "/usr/lib/python2.7/site-packages/virtualenv_support/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/index.py", line 15, in <module>
ImportError: cannot import name requests
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/bin/virtualenv", line 3, in <module>
    virtualenv.main()
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 944, in create_environment
    download=download,
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 900, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 796, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /root/root/.virtuale...mper_venv/bin/python - setuptools pip wheel failed with error code 1
what am I doing wrong  ?

**Comment by thomai** [comment]
I heard about some different solutions for that issue. Please try to downgrade python to 2.7.9 and upgrade pip and virtualenv.

**Comment by thomai** [comment]
Closing issue.
Reason: No further response.
